export const expandedGames = [
  {
    id: "sudoku",
    name: "Sudoku",
    description: "Complete linhas, colunas e blocos sem repetir.",
    category: "Inteligência",
    family: "logic",
  },
  {
    id: "nonograma",
    name: "Nonograma",
    description: "Números revelam uma imagem escondida.",
    category: "Inteligência",
    family: "logic",
  },
  {
    id: "labirinto",
    name: "Labirinto",
    description: "Encontre a saída entre corredores e becos.",
    category: "Inteligência",
    family: "logic",
  },
  {
    id: "sokoban",
    name: "Sokoban",
    description: "Empurre as caixas até os destinos.",
    category: "Estratégia",
    family: "logic",
  },
  {
    id: "hanoi",
    name: "Torres de Hanói",
    description: "Transfira os discos. Planeje cada movimento.",
    category: "Inteligência",
    family: "logic",
  },
  {
    id: "senha",
    name: "Código Secreto",
    description: "Descubra o código usando pistas.",
    category: "Inteligência",
    family: "logic",
  },
  {
    id: "nim",
    name: "Nim",
    description: "Retire peças e pense um turno à frente.",
    category: "Estratégia",
    family: "logic",
  },
  {
    id: "reversi",
    name: "Reversi",
    description: "Cerque as peças e conquiste o tabuleiro.",
    category: "Estratégia",
    family: "logic",
  },
  {
    id: "batalha",
    name: "Batalha Naval",
    description: "Localize os navios usando coordenadas.",
    category: "Estratégia",
    family: "logic",
  },
  {
    id: "pontes",
    name: "Pontos e Caixas",
    description: "Ligue os pontos e complete quadrados.",
    category: "Estratégia",
    family: "logic",
  },
  {
    id: "breakout",
    name: "Quebra-blocos",
    description: "Controle a raquete e destrua os blocos.",
    category: "Reflexos",
    family: "action",
  },
  {
    id: "pong",
    name: "Pong",
    description: "Defenda sua quadra e vença o adversário.",
    category: "Esportes",
    family: "action",
  },
  {
    id: "asteroides",
    name: "Asteroides",
    description: "Gire, acelere e abra caminho pelo espaço.",
    category: "Tiro",
    family: "action",
  },
  {
    id: "invasores",
    name: "Invasores",
    description: "Enfrente formações e ondas de inimigos.",
    category: "Tiro",
    family: "action",
  },
  {
    id: "runner",
    name: "Corrida de Obstáculos",
    description: "Pule os obstáculos e mantenha o ritmo.",
    category: "Corrida",
    family: "action",
  },
  {
    id: "voo",
    name: "Voo entre Torres",
    description: "Controle a altura e atravesse as passagens.",
    category: "Reflexos",
    family: "action",
  },
  {
    id: "jetpack",
    name: "Jetpack",
    description: "Gerencie o impulso e o combustível.",
    category: "Reflexos",
    family: "action",
  },
  {
    id: "esquiva",
    name: "Arena de Esquiva",
    description: "Mova-se pela arena e sobreviva ao cerco.",
    category: "Reflexos",
    family: "action",
  },
  {
    id: "pouso",
    name: "Pouso Lunar",
    description: "Poupe combustível e pouse com precisão.",
    category: "Inteligência",
    family: "action",
  },
  {
    id: "drift",
    name: "Circuito Drift",
    description: "Controle o carro e complete checkpoints.",
    category: "Carros",
    family: "action",
  },
  {
    id: "vinteum",
    name: "Vinte e Um",
    description: "Decida quando pedir ou parar. Sem apostas.",
    category: "Casuais",
    family: "casual",
  },
  {
    id: "dados",
    name: "Dados de Combinação",
    description: "Guarde os dados e monte combinações.",
    category: "Estratégia",
    family: "casual",
  },
  {
    id: "boliche",
    name: "Boliche",
    description: "Ajuste o lançamento e derrube os pinos.",
    category: "Esportes",
    family: "casual",
  },
  {
    id: "basquete",
    name: "Basquete",
    description: "Encontre o arco certo para a cesta.",
    category: "Esportes",
    family: "casual",
  },
  {
    id: "golfe",
    name: "Minigolfe",
    description: "Leia o campo e leve a bola ao buraco.",
    category: "Esportes",
    family: "casual",
  },
  {
    id: "arco",
    name: "Arco e Flecha",
    description: "Compense o vento e acerte o alvo.",
    category: "Esportes",
    family: "casual",
  },
  {
    id: "pesca",
    name: "Pesca",
    description: "Fisgue na hora certa e controle a linha.",
    category: "Casuais",
    family: "casual",
  },
  {
    id: "match3",
    name: "Combina 3",
    description: "Troque peças vizinhas e crie cascatas.",
    category: "Casuais",
    family: "casual",
  },
] as const;
export type ExpandedId = (typeof expandedGames)[number]["id"];
export const isExpandedId = (id: string): id is ExpandedId =>
  expandedGames.some((g) => g.id === id);
