const entries = [
  [
    "flood",
    "Maré de Cores",
    "Inteligência",
    "board",
    "Escolha uma cor para expandir a região do canto superior esquerdo. Cubra o tabuleiro em até 24 movimentos.",
  ],
  [
    "same",
    "Colapso de Cristais",
    "Casuais",
    "board",
    "Remova grupos de pelo menos dois cristais iguais. Eles caem e as colunas vazias se fecham. Limpe toda a grade.",
  ],
  [
    "peg",
    "Resta Um",
    "Estratégia",
    "board",
    "Selecione uma peça e uma casa vazia a duas casas de distância. Salte outra peça para removê-la. Deixe uma única peça.",
  ],
  [
    "knight",
    "Caminho do Cavalo",
    "Estratégia",
    "board",
    "Visite todas as casas uma vez usando saltos de cavalo: duas casas numa direção e uma na outra. Casas com ponto mostram os saltos legais.",
  ],
  [
    "queens",
    "Oito Rainhas",
    "Estratégia",
    "board",
    "Coloque oito rainhas sem compartilhar linha, coluna ou diagonal. Toque novamente para remover uma rainha.",
  ],
  [
    "latin",
    "Quadrado Latino",
    "Inteligência",
    "board",
    "Complete cada linha e coluna com 1 a 4 sem repetir. Selecione um número e uma casa livre; os números fixos são pistas.",
  ],
  [
    "takuzu",
    "Dupla Binária",
    "Inteligência",
    "board",
    "Complete a grade com zeros e uns: dois de cada por linha e coluna, sem três iguais seguidos e sem linhas ou colunas duplicadas.",
  ],
  [
    "sky",
    "Torres da Cidade",
    "Inteligência",
    "board",
    "Cada linha e coluna contém alturas 1 a 4. As pistas nas quatro bordas contam as torres visíveis, olhando a partir daquele lado.",
  ],
  [
    "futoshiki",
    "Desigualdades",
    "Inteligência",
    "board",
    "Complete linhas e colunas com 1 a 4. Respeite os sinais de maior e menor entre as casas indicadas.",
  ],
  [
    "magic",
    "Quadrado Mágico",
    "Inteligência",
    "board",
    "Use cada número de 1 a 9 uma vez. Todas as linhas, colunas e as duas diagonais devem somar 15.",
  ],
  [
    "fifteen",
    "Deslize 15",
    "Inteligência",
    "board",
    "Toque numa peça vizinha ao espaço vazio. Organize os números 1 a 15 e deixe o espaço no canto inferior direito.",
  ],
  [
    "rotate",
    "Mosaico Giratório",
    "Inteligência",
    "board",
    "Cada toque gira um bloco 2 por 2 no sentido horário. Recrie a referência numérica ao lado do tabuleiro.",
  ],
  [
    "pipes",
    "Rede de Tubos",
    "Inteligência",
    "board",
    "Gire os tubos para ligar a entrada à saída. Toda conexão deve ter uma conexão de retorno; nenhuma ponta pode ficar aberta.",
  ],
  [
    "laser",
    "Espelhos e Luz",
    "Inteligência",
    "board",
    "Alterne os espelhos / e \\ para conduzir o raio da entrada à saída. A linha mostra o trajeto real e colisões com as bordas.",
  ],
  [
    "loop",
    "Circuito Único",
    "Inteligência",
    "board",
    "Ative segmentos para formar um único circuito fechado que visite todas as casas. Cada casa deve ter exatamente duas conexões.",
  ],
  [
    "links",
    "Trilhas Numeradas",
    "Inteligência",
    "board",
    "Selecione uma cor e conecte seus dois terminais por casas vizinhas. Cubra todas as casas sem cruzar trilhas. Use Apagar para corrigir.",
  ],
  [
    "colorsort",
    "Pilhas de Cores",
    "Inteligência",
    "board",
    "Escolha a pilha de origem e depois o destino. Mova o topo sobre a mesma cor ou uma pilha vazia. Separe todas as cores em pilhas uniformes.",
  ],
  [
    "watersort",
    "Laboratório de Líquidos",
    "Inteligência",
    "board",
    "Escolha dois frascos. Despeje todo o grupo de cor do topo que couber sobre uma cor igual ou num frasco vazio. Separe as cores.",
  ],
  [
    "slideblock",
    "Saída Livre",
    "Estratégia",
    "board",
    "Selecione um veículo e use as setas para deslizar no seu eixo. Libere a saída e leve o carro vermelho até a borda direita.",
  ],
  [
    "memorypath",
    "Trilha de Memória",
    "Memória",
    "board",
    "Observe a trilha, toque em Ocultar trilha e repita as casas na ordem correta. Um erro encerra a tentativa.",
  ],
  [
    "gomoku",
    "Cinco em Linha",
    "Estratégia",
    "board",
    "Você joga com X contra O. Forme cinco marcas consecutivas na horizontal, vertical ou diagonal antes do adversário.",
  ],
  [
    "hex",
    "Hex Conexões",
    "Estratégia",
    "board",
    "Conecte as bordas de cima e baixo com X. O adversário O tenta conectar esquerda e direita; casas têm seis vizinhos.",
  ],
  [
    "ataxx",
    "Colônia Ataxx",
    "Estratégia",
    "board",
    "Selecione X e um destino livre até duas casas. Um passo clona; dois saltam. Vizinhos do destino mudam de lado. Domine mais casas.",
  ],
  [
    "isolation",
    "Ilhas em Duelo",
    "Estratégia",
    "board",
    "Mova X para uma casa vizinha vazia e depois remova uma casa livre. O rival faz o mesmo. Imobilize O antes que ele imobilize você.",
  ],
  [
    "breakthrough",
    "Linha de Avanço",
    "Estratégia",
    "board",
    "Selecione X e avance uma casa para cima, reto ou diagonal. Capture O na diagonal. Alcance a última linha ou elimine os rivais.",
  ],
  [
    "mancala",
    "Mancala",
    "Estratégia",
    "board",
    "Distribua as sementes de uma de suas seis casas em sentido anti-horário, pulando o depósito rival. Última semente no seu depósito dá outra vez; captura usa a casa oposta.",
  ],
  [
    "chomp",
    "Chocolate Tático",
    "Estratégia",
    "board",
    "Toque num quadrado para comer ele e tudo abaixo e à direita. O canto superior esquerdo é venenoso: quem o come perde.",
  ],
  [
    "territory",
    "Fronteiras",
    "Estratégia",
    "board",
    "Conquiste uma casa vazia ao lado do seu território X. O rival expande O. Ao ocupar a grade, vence quem controla mais casas.",
  ],
  [
    "arithmetic",
    "Cálculo Relâmpago",
    "Inteligência",
    "quiz",
    "Resolva dez operações. Dificuldades maiores aumentam os valores e incluem multiplicação. Cada resposta correta vale 100 pontos.",
  ],
  [
    "fractions",
    "Duelo de Frações",
    "Inteligência",
    "quiz",
    "Compare duas frações e escolha menor, igual ou maior. Compare seus valores, não apenas os numeradores. Complete dez rodadas.",
  ],
  [
    "primes",
    "Detector de Primos",
    "Inteligência",
    "quiz",
    "Decida se o número é primo. Um primo tem exatamente dois divisores positivos; 1 não é primo. Complete dez rodadas.",
  ],
  [
    "equation",
    "Incógnita",
    "Inteligência",
    "quiz",
    "Descubra x em cada equação linear. Resolva dez equações; a dificuldade aumenta os coeficientes.",
  ],
  [
    "twentyfour",
    "Desafio 24",
    "Inteligência",
    "quiz",
    "Use os quatro números mostrados uma única vez com +, −, ×, ÷ e parênteses para formar 24. Digite a expressão e confirme.",
  ],
  [
    "numsequence",
    "Próximo Número",
    "Inteligência",
    "quiz",
    "Encontre o próximo termo da progressão. Ela pode ser aritmética, geométrica ou usar diferenças crescentes.",
  ],
  [
    "anagram",
    "Oficina de Anagramas",
    "Inteligência",
    "quiz",
    "Reorganize as letras para descobrir a palavra. A pista indica o significado. Digite sem acentos e confirme.",
  ],
  [
    "hangman",
    "Forca de Palavras",
    "Inteligência",
    "quiz",
    "Descubra a palavra escolhendo letras. Você pode errar seis vezes. Letras repetidas não gastam tentativas.",
  ],
  [
    "wordsearch",
    "Caça-palavras",
    "Inteligência",
    "quiz",
    "Encontre as palavras da lista na grade. Escolha a primeira e a última letra; as palavras podem estar na horizontal, vertical ou diagonal.",
  ],
  [
    "stroop",
    "Cor em Conflito",
    "Reflexos",
    "quiz",
    "Escolha a cor da tinta da palavra, ignorando o que ela diz. Complete dez rodadas com precisão.",
  ],
  [
    "oddone",
    "Intruso Lógico",
    "Inteligência",
    "quiz",
    "Escolha o único número que não segue a regra indicada. Complete dez rodadas; observe os divisores e a paridade.",
  ],
  [
    "estimate",
    "Olho de Águia",
    "Memória",
    "quiz",
    "Observe o grupo de pontos, oculte a imagem e estime a quantidade. A proximidade da resposta define os pontos.",
  ],
  [
    "rhythm",
    "Pulso Musical",
    "Reflexos",
    "motion",
    "Toque nas faixas 1 a 4 ou use essas teclas quando as notas cruzarem a linha. Precisão dá combos; erros custam vidas.",
  ],
  [
    "balloons",
    "Balões em Fuga",
    "Reflexos",
    "motion",
    "Toque nos balões ou use a tecla do número mostrado antes que escapem pelo teto. Evite os balões marcados com ×.",
  ],
  [
    "meteors",
    "Escudo Meteórico",
    "Tiro",
    "motion",
    "Mova o escudo com as setas ou A/D para interceptar meteoros antes que atinjam a base. A base suporta três impactos.",
  ],
  [
    "stack",
    "Torre de Precisão",
    "Casuais",
    "motion",
    "Use Ação ou espaço para soltar cada bloco sobre o anterior. A parte sem apoio cai; construa doze andares.",
  ],
  [
    "balance",
    "Equilíbrio Orbital",
    "Reflexos",
    "motion",
    "Use esquerda e direita para inclinar a plataforma e equilibrar a esfera por 45 segundos. Velocidade e inclinação alteram o movimento.",
  ],
  [
    "ski",
    "Slalom Alpino",
    "Esportes",
    "motion",
    "Deslize com as setas ou A/D. Atravesse as portas verdes e evite as árvores. Aceleração lateral exige antecipar cada curva.",
  ],
  [
    "crossroad",
    "Travessia Urbana",
    "Casuais",
    "motion",
    "Use setas ou WASD para atravessar as seis faixas sem tocar nos veículos. Alcance a calçada superior três vezes.",
  ],
  [
    "rope",
    "Salto no Pêndulo",
    "Reflexos",
    "motion",
    "Use Ação ou espaço para saltar quando a corda passar pelos seus pés. A gravidade limita a altura; complete vinte voltas.",
  ],
  [
    "turret",
    "Sentinela",
    "Tiro",
    "motion",
    "Gire a mira com esquerda e direita e dispare com Ação ou espaço. Destrua os inimigos antes de chegarem à base.",
  ],
  [
    "ricochet",
    "Ricochete Tático",
    "Tiro",
    "motion",
    "Ajuste a mira com as setas e lance a esfera com Ação ou espaço. Ela rebate nas paredes; destrua todos os alvos em oito disparos.",
  ],
] as const;

export const newGames = entries.map(([id, name, category, family, help]) => ({
  id,
  name,
  category,
  family,
  help,
  description: help.split(". ")[0] + ".",
}));
export type NewGameId = (typeof entries)[number][0];
export type BoardId = Extract<
  (typeof entries)[number],
  readonly [string, string, string, "board", string]
>[0];
export const isNewGameId = (id: string): id is NewGameId =>
  newGames.some((g) => g.id === id);
